spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: qazwsxedc7410
    type: com.alibaba.druid.pool.DruidDataSource

  #thymeleaf
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  #redis
  redis:
    host: 118.31.103.27
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-idle: 5000
        max-wait: 10000
        max-active: 5000
        min-idle: 0
    password: 123456
    database: 0
  #静态资源配置
  resources:
    add-mappings: true
    cache:
      period: 3600
    chain:
      cache: true
      enabled: true
      html-application-cache: true
    static-locations: classpath:/static/

  #消息队列
  rabbitmq:
    host: 118.31.103.27
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true

    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

mybatis:
  type-aliases-package: com.yucaihuang.seckillspringboot.pojo
  mapper-locations: classpath:Mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

#日志文件位置配置
logging:
  file:
    name: seckill-spring-boot.log
    path: /log

