spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: qazwsxedc7410
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.yucaihuang.seckillspringboot.pojo
  mapper-locations: classpath:Mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

#日志文件位置配置
logging:
  file:
    name: seckill-spring-boot.log
    path: /
